language: ruby

rvm:
  - 2.2.2
  - 2.3.1

before_install: "rm ${BUNDLE_GEMFILE}.lock"

before_script: "bundle update"

sudo: false

cache: bundler

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.2-stable
